### ISSUE TITLE
Python not recognizing get_qubit/get_qubits despite being most up to date version.

### ISSUE THREAD

**Issue by nskjellum** [tqsd/QuNetSim#148]
**Describe the bug**
I have installed qunet sim using pip into my python venv, which installed version (0.1.2.post3). I have attempted to use the up to date get_qubit, get_data_qubits, functions, but these are not recognized when I attempt to use them. It provides the following error:

AttributeError: 'Host' object has no attribute 'get_qubits'

**To Reproduce**
1. Install qunetsim. 
2. Create program that uses "get_qubits" correctly and execute. 

**Expected behavior**
Method should be accepted attribute of host. 

**System:**
 - OS: Ubuntu WSL
 - Python Version:  3.9

**Comment by stephendiadamo** [comment]
I haven't yet updated the PyPI library yet, I can do this in the coming days. 
In the mean time, you can use the source code directly since it will be the latest release.

**Comment by NadineM1012** [comment]
I have the same issue : AttributeError: 'Host' object has no attribute 'get_qubits' with python version = 3.9.16 running on google colab

**Comment by stephendiadamo** [comment]
Hello, sorry, I no longer have the ability to merge PRs without a secondary reviewer and so this will need some more time. The pip version is still out of date. To overcome this, you can use QuNetSim from source (i.e., clone it).

**Comment by marcjofreProf** [comment]
Most of the examples have some errors that prevent them from running.

I have the same issue: AttributeError: 'Host' object has no attribute 'get_qubit'

How can it be installed in google Colab the latest release?

**Comment by marcjofreProf** [comment]
> I have the same issue : AttributeError: 'Host' object has no attribute 'get_qubits' with python version = 3.9.16 running on google colab

I seems that if I change to get_data_qubit, things seem to work. Then there are other error appearing

**Comment by stephendiadamo** [comment]
> > I have the same issue : AttributeError: 'Host' object has no attribute 'get_qubits' with python version = 3.9.16 running on google colab
> 
> I seems that if I change to get_data_qubit, things seem to work. Then there are other error appearing

Yes, the PyPi version is not up to date with the documentation. The change is simply a refactor of the method name. This is the temporary workaround. We will update the PyPi version this week. Sorry for the trouble.

**Comment by stephendiadamo** [comment]
The PyPi version has been updated and the problem solved.

**Comment by marcjofreProf** [comment]
Thanks. The newest pypi release does not install properly:

raceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-8-6f63fc8a596d>"](https://localhost:8080/#), line 2, in <cell line: 1>
    import qunetsim

  File "/usr/local/lib/python3.9/dist-packages/qunetsim/__init__.py", line 1, in <module>
    from .components import Host, Network

  File "/usr/local/lib/python3.9/dist-packages/qunetsim/components/__init__.py", line 1, in <module>
    from .host import Host

  File "/usr/local/lib/python3.9/dist-packages/qunetsim/components/host.py", line 1368
    )
    ^
SyntaxError: unmatched ')'

**Comment by stephendiadamo** [comment]
Please try again, it's been fixed in a second new version.

Thanks,
Stephen

**Comment by marcjofreProf** [comment]
Now seem to work

thanks
