### ISSUE TITLE
Create connection objects

### ISSUE THREAD

**Issue by stephendiadamo** [tqsd/QuNetSim#42]
Connections at the moment are booleans (connected or not). We should create an object, one for classical one for quantum, that models the connections better.

**Comment by stephendiadamo** [comment]
**Meeting discussion:** (16.07.2020)
- Generalize the quantum connections so that channel models (e.g. depolarizing and erasure channels) can be implemented
- Think about putting the queues of the network into the end points of the links (but let's leave this until later)
- Start with quantum channel first, just the modeling part, as a branch from the latest QuNetSim master, moving some of previous work over and we'll work from there regarding building up the objects to be flexible / customizable

**Comment by AnirbanHFX** [comment]
Please assign the following pull request to this project -
https://github.com/tqsd/QuNetSim/pull/53
