### ISSUE TITLE
QuNetSim Issues

### ISSUE THREAD

**Issue by william-rittmeyer** [tqsd/QuNetSim#46]
**Describe the bug**

I am trying to use your GHZ demo in order to build  and demonstrate a blockchain consensus algorithm for a project I am working on. I have gone through your installation, set up the virtual environment and have successfully been able to run templater.py and the test python script that is created from it.

I do not have a C++ compiler so I did what the instructions told me and removed the ProjectQ requirement in requirements.txt. One thing I have noticed is that the GHZ code at https://tqsd.github.io/QuNetSim/_build/examples/anonymous_transfer.html is different from the one in the repository. Regardless, I failed to have either work... The one in the repository did not work because it require ProjectQ (which I previously mentioned I omitted). I copied the code in the html into a file named GHZ.py and ran the code failed as seen below.

**To Reproduce**
1. Go to ''https://tqsd.github.io/QuNetSim/_build/examples/anonymous_transfer.html
2. Copy code and input code into file called GHZ.py in main directory folder
3. Run source ./venv/bin/activate outside directory folder
4. cd ./QuNetSim
5. Run python3 GHZ.py
6. See error

**Expected behavior**
I expected to see the GHZ state demo work, so I can continue the project

**Screenshots**
![GHZ](https://user-images.githubusercontent.com/60793567/85421910-fe787e80-b542-11ea-9ca1-5494aef9865f.png)

**System:**
 - OS: Ubuntu 20.04
 - Python Version: Python 3.8

**Additional context**
I am just starting to get comfortable with your project. I found it to be the best quantum network simulator I have seen. I want to learn as much as I can and may want to build my own backend eventually. I would appreciate an guidance and/or help.

**Comment by stephendiadamo** [comment]
Thanks for your report. 

I'll look into this right away. We've made some updates lately and maybe the issue is solved with a version update. 

I'll post back with an update.

**Comment by stephendiadamo** [comment]
I was able to reproduce this and now I'm looking into the issue.

**Comment by stephendiadamo** [comment]
@witt-designs If you update the pip library to 0.1.0post3, we've (@benjione and I) uploaded a new version with the fix.

Thanks for pointing out the bug!
