### ISSUE TITLE
ProjectQ can not be installed via pip on github

### ISSUE THREAD

**Issue by benjione** [tqsd/QuNetSim#58]
The version of ProjectQ we use can not be installed via pip, because of some setup error on their side.

1. Run unittest on github

Solution possibilities:
1. Remove from requirements for unittests and make users to install it manually if they want to use ProjectQ
2. Check for new versions of ProjectQ which are pip installable.

**Comment by stephendiadamo** [comment]
I think 2 pull requests have removed ProjectQ installation... I'll close this issue for now.
