### ISSUE TITLE
GHZ measurement stuck over 13 nodes

### ISSUE THREAD

**Issue by AleMuzzi** [tqsd/QuNetSim#70]
I wrote the following code to test the capability of the framework to share a GHZ state over a large amount of nodes.
Everything works really good till when the nodes number is under 13: above 13 nodes the code stucks at the first qubit measurement.
Debugging the framework I found out that the code **is stuck at line 332 of python3.8/site-packages/eqsn/gates.py** :
`res = ret.get()`.
It seems to me that someone steals the object just put in the queue from line 331 of the same file because right after the end of the put() at line 331 the queue is empty again, but I didn't find the actual cause of the bug.
Am I doing something wrong? 

```python
from qunetsim.components import Host
from qunetsim.components import Network
from qunetsim.objects import Logger
from qunetsim.backends.projectq_backend import ProjectQBackend

Logger.DISABLED = True

SCALAR_NETWORK_NODES_NUMBER = 14
NET_TOPOLOGY_STAR = True
NET_TOPOLOGY_POINT_TO_POINT = False
PRINT_MEASUREMENTS = True


def main():
    network = Network.get_instance()
    network.delay = 0.1

    nodes = []
    hosts = []
    hostCount = 0

    # region Large Scalable Network

    print("Building a %s network with %d hosts..." % (("star" if NET_TOPOLOGY_STAR else "point to point"), SCALAR_NETWORK_NODES_NUMBER))

    for i in range(0, SCALAR_NETWORK_NODES_NUMBER):
        hostName: str = "node" + str(hostCount)
        hostCount += 1
        nodes.append(hostName)
        hosts.append(Host(hostName))

        if NET_TOPOLOGY_STAR:
            if i > 0:
                hosts[i].add_connection(hosts[0].host_id)
                hosts[0].add_connection(hosts[i].host_id)

        elif NET_TOPOLOGY_POINT_TO_POINT:
            if i > 0:
                hosts[i].add_connection(hosts[i - 1].host_id)
                hosts[i - 1].add_connection(hosts[i].host_id)

    back = ProjectQBackend()
    network.start(nodes, back)

    for host in hosts:
        host.start()
        network.add_host(host)

    # endregion

    # building the GHZ state for all the hosts
    print("Sending GHZ states...")
    share_list = [host.host_id for host in hosts[1:]]
    q_id1, ack_received = hosts[0].send_ghz(share_list, await_ack=True)

    print("%s received ACK from all? %s" % (hosts[0].host_id, str(ack_received)))

    qubits = []
    for i in range(len(hosts)):
        qubits.append(hosts[i].get_ghz(hosts[0].host_id, q_id1, wait=10))

    for i in range(len(qubits)):
        if qubits[i] is None:
            raise ValueError("{}'s qubit is none".format(hosts[i].host_id))

    print("Performing measurements...")
    measurements = []
    for i in range(len(qubits)):
        print("Measuring host %s..." % hosts[i].host_id)
        measurements.append(qubits[i].measure())

    if PRINT_MEASUREMENTS:
        print("results of measurements are: ", end='')

        for measurement in measurements:
            print(measurement, end='')
        print()

    correct_count = 1
    error = True
    while measurements[0] == measurements[correct_count]:
        correct_count += 1
        if correct_count == len(measurements):
            print("GHZ entanglement success!")
            error = False
            break

    if error:
        print("GHZ entanglement error!")

    network.stop(True)
    exit()


if __name__ == '__main__':
    main()
```

**Comment by stephendiadamo** [comment]
Thanks for the bug report, I'll test it as well and update you with any progress towards fixing it. Your code looks fine at first glance, and it runs fine for me as well. One thing to note is we're using raw matrices here so a GHZ state across 14 hosts may start to push the limit... The state matrix has dimension 2^14 x 2^14 = 268,435,456, so this likely hits the upper limit of what can be done with QuNetSim with EQSN backend.

One thing to try is, that might be what you intended, is that you imported ProjectQ backend, but actually the backend is not set on the hosts, so it's using the default EQSN backend. ProjectQ might be more optimized for this kind of thing... 

I'll try it myself and report back.

**Comment by stephendiadamo** [comment]
Here's an update: 

With 14 hosts on my computer, I get the same bottleneck. On another computer running the C version of ProjectQ as the backend, it would run up to ~25 hosts in a few seconds. I've also updated the PyPi project to version 0.1.1.post3 which contains a new backend: QuTiP. QuTiP can also handle a higher number of hosts.

You can try those two backends and see if it works for you. If it improves for you, then I will close this issue.

**Comment by AleMuzzi** [comment]
Hi, thanks for the fast response.
Honestly, I thought that hosts would have inherited the backend from the network they are added to, now I saw the optional argument in Host's constructor.
Thinking about it though, it's better that it works this way because I suppose that a host can be added to more than one network that might work with different backends.

I can confirm you that if the hosts are running on **ProjectQ** backend the script performs fluently up to 23-24 hosts, than the time demand starts to grow exponentially:
**23** 0:00:02.539018
**24** 0:00:03.297146
**25** 0:00:06.699881
**26** 0:00:15.285010
**27** 0:00:28.608917
**28** 0:01:02.755283
**29** 0:03:36.598100

I have also done a few tests with **QuTip** backend on both network and hosts with the following results:
**13** 0:00:01.064913
**14** 0:00:03.667216
**15** 0:00:16.009192
**16** 0:02:00.250605
**17** ValueError: maximum supported dimension for an ndarray is 32, found 34
**20** ValueError: maximum supported dimension for an ndarray is 32, found 40
**23** MemoryError: Unable to allocate 1.00 PiB for an array with shape (8388608, 8388608) and data type complex128

Note: the time mesurements start right before the measurement for cycle and end right after that, all the print in between have been commented out as follows:

```python
start_time = datetime.now()
measurements = []
for i in range(len(qubits)):
    # print("Measuring host %s..." % hosts[i].host_id)
    measurements.append(qubits[i].measure())
elapsed_time = datetime.now() - start_time
print("Elapsed time: " + str(elapsed_time))
```

At the moment, the best backend for a large scale GHZ seems to be ProjectQ.

**Comment by stephendiadamo** [comment]
Actually your suggestion of inheriting from the network makes a lot of sense. Currently QuNetSim is using a Network singleton so there can only be one network. 

Thanks for your timing  analysis. I think just playing around with the various backends is the best approach. If you know of other qubit simulators that might further improve the run time, feel free to suggest them in another issue and we can add them in.

Hopefully you've got a clearer picture of the limitations of QuNetSim. Feel free to post any other questions / comments. I'll close this thread for now.
