### ISSUE TITLE
The plotting functions in Network class not working 

### ISSUE THREAD

**Issue by Shiro-Raven** [tqsd/QuNetSim#83]
The `draw_classical_network` and `draw_quantum_network` functions are not working. I receive the error `ValueError: Received invalid argument(s): hold` when I attempted to plot a network.

1. Simply create a network and add some nodes.
2. Invoke one of the plotting functions.

**Expected behavior**
A NetworkX graph showing the built network. 

**System:**
 - OS: Ubuntu 20.04
 - Python Version: Python 3.8

**Comment by stephendiadamo** [comment]
Thanks for reporting. Will have an update this week.

**Comment by stephendiadamo** [comment]
Fixed in 0.1.2.post0.
