### ISSUE TITLE
Implement various QKD protocols.

### ISSUE THREAD

**Issue by stephendiadamo** [tqsd/QuNetSim#90]
There are quite a few different varieties of QKD (https://en.wikipedia.org/wiki/List_of_quantum_key_distribution_protocols).

We should implement as many as possible in QuNetSim.

List of QKD protocols: 
- [x] BB84
- [x] E91 
- [x] B92
- [x] BBM92
- [x] ...

**Comment by anushkrishnav** [comment]
I would love to work on BB84
Can you please share some guide or sample for me too look into and prep.
More details on the task would be great

**Comment by fvista** [comment]
I am interested too.

**Comment by stephendiadamo** [comment]
Here is a sample in QuNetSim that does a version of QKD based on BB84: https://tqsd.github.io/QuNetSim/examples/QKD.html

**Comment by zemenfes-afk** [comment]
I need to look at the use of matlibplot? the network topology graphically?

**Comment by stephendiadamo** [comment]
> I need to look at the use of matlibplot? the network topology graphically?
> 

If I understand correctly, you're asking what is the use of matplotlib in QuNetSim? If so, then yes it's used to graphically show the network topology.

**Comment by anushkrishnav** [comment]
> Here is a sample in QuNetSim that does a version of QKD based on BB84: https://tqsd.github.io/QuNetSim/examples/QKD.html

So BB84 is already worked on ?

**Comment by stephendiadamo** [comment]
@anushkrishnav  In a way yes, but it is a modified implementation of it and doesn't perform all the steps for a QKD protocol. For example, it lacks the explicit stage of detecting an eavesdropper. Essentially key sifting is not implemented according to the standard approach one would use.

**Comment by sashofthedark** [comment]
Hi, I would like to work on implementing the B92 protocol during the unitaryHACK event.

**Comment by sashofthedark** [comment]
> Here is a sample in QuNetSim that does a version of QKD based on BB84: https://tqsd.github.io/QuNetSim/examples/QKD.html

As far as I understand, this example lacks the interaction with Bob! Alice and Eve communicate undisturbed.

**Comment by zemenfes-afk** [comment]
https://github.com/Interlin-q/Interlin-q/issues/42#issue-893234275

**Comment by stephendiadamo** [comment]
We've had 2 or 3 entries for BB84 and one for E91. B92 is also in progress. Any other are still open!

**Comment by pritamsinha2304** [comment]
@stephendiadamo 
I have 2 question/confusion-
1) So I am trying all the QKD protocols possible, but I am making these protocols in 2 files. One with interception and another without interception. Should I upload 2 files of each protocols or one ? Like this BB84 is without interception and I have another BB84 with interception haven't uploaded it yet.

2) This is regarding E91 and BBM92, I am using send_epr and get_epr to get entangle state, but how do I sniff it...I mean that sniffing classical and quantum is not working for epr. How should I approach it, some ideas would be useful ?

**Comment by stephendiadamo** [comment]
>So I am trying all the QKD protocols possible, but I am making these protocols in 2 files. One with interception and another without interception. Should I upload 2 files of each protocols or one ? Like this BB84 is without interception and I have another BB84 with interception haven't uploaded it yet.

I think it's better just to have one file and the option to turn the interception off. 

>This is regarding E91 and BBM92, I am using send_epr and get_epr to get entangle state, but how do I sniff it...I mean that sniffing classical and quantum is not working for epr. How should I approach it, some ideas would be useful ?

You can also send an EPR pair by creating 2 qubits and entangling them (Hadamard on the first qubit and CNOT with the first qubit as control) and then send that qubit using `send_qubit`. The difference will be that the qubit will not arrive in the EPR storage but rather as a data qubit.

**Comment by pritamsinha2304** [comment]
> > So I am trying all the QKD protocols possible, but I am making these protocols in 2 files. One with interception and another without interception. Should I upload 2 files of each protocols or one ? Like this BB84 is without interception and I have another BB84 with interception haven't uploaded it yet.
> 
> I think it's better just to have one file and the option to turn the interception off.
> 
> > This is regarding E91 and BBM92, I am using send_epr and get_epr to get entangle state, but how do I sniff it...I mean that sniffing classical and quantum is not working for epr. How should I approach it, some ideas would be useful ?
> 
> You can also send an EPR pair by creating 2 qubits and entangling them (Hadamard on the first qubit and CNOT with the first qubit as control) and then send that qubit using `send_qubit`. The difference will be that the qubit will not arrive in the EPR storage but rather as a data qubit.

Ok Got it. Thanks for the help. I will combine both files in one

**Comment by sashofthedark** [comment]
> @stephendiadamo
> I have 2 question/confusion-
> 
> 1. So I am trying all the QKD protocols possible, but I am making these protocols in 2 files. One with interception and another without interception. Should I upload 2 files of each protocols or one ? Like this BB84 is without interception and I have another BB84 with interception haven't uploaded it yet.
> 2. This is regarding E91 and BBM92, I am using send_epr and get_epr to get entangle state, but how do I sniff it...I mean that sniffing classical and quantum is not working for epr. How should I approach it, some ideas would be useful ?

Hello,
Note that I am working on B92 protocol including eavesdropping (as discussed in this thread) and am opening a PR today.

**Comment by pritamsinha2304** [comment]
What is the last qkd ?

**Comment by stephendiadamo** [comment]
All QKD protocols listed in the issue have been completed, as well as the additional one you've done.

There aren't any new claimed protocols yet so anything else  would be open.
